### ISSUE TITLE
生成头像方式问题

### ISSUE THREAD

**Issue by toxmc** [lincanbin/Material-Design-Avatars#3]
可以通过用户上传图片，生成头像？还是只能通过字来生成头像

**Comment by lincanbin** [comment]
通过字，自动提取用户名首字生成头像。

**Comment by toxmc** [comment]
就是说暂不支持用户自定义上传图片，然后生成头像。

**Comment by lincanbin** [comment]
一个库做一个事，这个库的功能就是根据用户名来生成头像，怎么可能支持、也不需要支持上传头像。
而且这只是一个PHP库，用户上传头像必然要再前端再加一个表单。

如果想要上传头像功能，可以再引入库：
https://github.com/lincanbin/PHP-Image-Resize-Class
上面这个库可以从网络或者表单获取用户头像，然后截取中间正方形的部分，再根据设定自动切割成不同尺寸的头像。

**Comment by lincanbin** [comment]
https://www.94cb.com/
这个生成头像的库的具体应用，可以在这个网站看到。

**Comment by toxmc** [comment]
嗯，thank you.
