### ISSUE TITLE
字体文件坏掉了

### ISSUE THREAD

**Issue by multiarrow** [lincanbin/Material-Design-Avatars#4]
头像显示不了文字，发现是fonts文件夹中的字体文件坏掉了 ，我把Carbon-Forum中相应的字体文件复制过来覆盖就可以了

**Comment by lincanbin** [comment]
那文件我都没去动过啊。
https://github.com/lincanbin/Material-Design-Avatars/commits/master/src/fonts/SourceHanSansCN-Normal.ttf

只有一版的history。

**Comment by lincanbin** [comment]
我又特地试了下，是正常的。

**Comment by multiarrow** [comment]
知道原因了，是我的错。。。因为不想clone整个项目，我就直接在字体文件的链接上右键“另存为”，保存的文件名是SourceHanSansCN-Normal.ttf，不过用notepad打开查看的内容却是html。用git clone整个项目下来的话就没这个问题。

**Comment by lincanbin** [comment]
通过RAW下载到的才是源文件
